### ISSUE TITLE
Setup instructions no longer work

### ISSUE THREAD

**Issue by alexslade** [skylightio/skylight-phoenix#7]
Hi team, 

I've tried to follow along with a Phoenix 1.3 app, and couldn't get this up and running. `web.ex` no longer exists in Phoenix 1.3, and I see this error when compiling. 

```
== Compilation error in file lib/envy/repo.ex ==
** (CompileError) lib/envy/repo.ex:3: module Skylight.Ecto.Repo is not loaded and could not be found
    (elixir) expanding macro: Kernel.use/1
    lib/envy/repo.ex:3: Envy.Repo (module)
    (elixir) lib/kernel/parallel_compiler.ex:198: anonymous fn/4 in Kernel.ParallelCompiler.spawn_workers/6
```

**Comment by wagenet** [comment]
Thanks for the heads up. We'd still love to support Phoenix but it's been quite low on our priority list. One of our other developers, @zvkemp is going to look into this and see if we can get things operational again.

**Comment by zvkemp** [comment]
@heeton Your error message makes me think Skylight didn't compile correctly. Please run `mix deps.update skylight` and `mix compile` to make sure you have the latest master (we recently merged a commit that should fix this).

Ecto instrumentation works by creating a wrapper module around `MyApp.Repo` (known to the runtime as `MyApp.Repo.Skylight`). In previous versions of Phoenix, the controller macro automatically aliased `MyApp.Repo` to `Repo`. Since the 1.3 update, since schema access now happens in Contexts by default, this alias needs to happen in your context module (or anywhere else you use `Repo`), e.g.

```elixir
defmodule MyApp.Accounts do
  alias MyApp.Repo.Skylight, as: Repo
  ...
end
```

**Comment by alexslade** [comment]
Thanks @zvkemp. I've updated things, and updated the setup like you suggested, and am no longer getting that error. 

Some info is being sent to Skylight, but I see a warning: "Your Skylight agent is out of date" and no metrics for my endpoints, just top-level response times. 

Is that because your agent is still alpha? Or should I be seeing a breakdown like I would with the ruby agent? 

I'm also getting weird freezes in my app, that I can't seem to debug. It appears to be something to do with the skylight daemon - requests to my app are just hanging (for 30+ seconds) occasionally after 2-3 requests.
